---
# Defaults for database config
mongodb_aptkey: 4B7C549A058F8B6B
mongodb_repository: deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.2 multiverse
mongodb_packagename: mongodb-org
mongodb_confpath: /etc/mongod.conf
db_directory: /data/db
