---
- name: Creating database directory '/data/db'
  file:
    path: /data/db
    state: directory

- name: Generating configuration files
  copy:
    src: ../files/mongod.conf-replset.tmp
    dest: /etc/mongod.conf
    owner: root
    group: root
    mode: '0644'

- name: Restarting MongoDB service
  service:
    name: mongod
    state: restarted

#- name: Removing possible locks
#  file:
#    path: /var/lib/mongodb/mongod.lock
#    state: absent
#
#- name: Restarting MongoDB service
#  service:
#    name: mongod
#    state: restarted
