---
- name: Appending replicaset configuration
  blockinfile:
    path: '{{ mongodb_confpath }}'
    block: |
      replication:
        replSetName: rs0
  become: yes

- name: Creating database directory
  file:
    path: '{{ db_directory }}'
    state: directory
  become: yes

- name: Restarting MongoDB service
  service:
    name: mongod
    state: restarted
  become: yes

- name: Updating apt cache
  apt:
    update_cache: yes
  become: yes