---
- name: Importing MongoDB public key from Ubuntu key server
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: '{{ mongodb_aptkey }}'
  become: yes

- name: Adding MongoDB repo to sources.list.d
  apt_repository:
    repo: '{{ mongodb_repository }}'
    state: present
    filename: mongodb-org-4.2
    update_cache: yes
  become: yes

- name: Installing MongoDB using apt
  apt:
    name: '{{ mongodb_packagename }}'
    state: present
  become: yes

- name: Starting MongoDB service
  service:
    name: mongod
    state: restarted
  become: yes