---
- name: Disable db authorization to init replset
  lineinfile:
    path: '{{ mongodb_confpath }}'
    regexp: '^authorization: enabled'
    state: absent
  become: yes

- name: Initializing one node replica set
  mongodb_replicaset:
    login_host: localhost
    login_port: 27017
    login_user: admin
    login_password: nimda
    login_database: admin
    replica_set: rs0
    members: localhost:27017
    validate: no
  become: yes

- name: Waiting for replica set to wrap up
  pause:
    seconds: 10

- name: Creating admin user
  mongodb_user:
    database: '{{ admin_db }}'
    name: '{{ admin_name }}'
    password: '{{ admin_pw }}'
    replica_set: rs0
    roles: root
    state: present

- name: Appending auth configuration
  blockinfile:
    path: '{{ mongodb_confpath }}'
    block: |
      replication:
        replSetName: rs0

      security:
        authorization: enabled
  become: yes

- name: Restarting MongoDB service
  service:
    name: mongod
    state: restarted
  become: yes

- name: Waiting for replica set to wrap up
  pause:
    seconds: 10

- name: Create user 'milvus'
  mongodb_user:
    login_database: '{{ admin_db }}'
    login_user: '{{ admin_name }}'
    login_password: '{{ admin_pw }}'
    database: '{{ user_db }}'
    name: '{{ user_name }}'
    password: '{{ user_pw }}'
    roles: readWrite
    state: present
