---
- name: Updating apt cache
  apt:
    update_cache: yes
  become: yes

- name: Installing pip from Ubuntu repositories
  apt:
    name: python-pip
    state: present
  become: yes

- name: Installing dependencies
  pip:
    name:
    - pymongo
    - python-apt
    executable: pip
  become: yes
