- name: Updating apt cache
  apt:
    update_cache: yes

- name: Installing pip from Ubuntu repositories
  apt:
    name: python-pip
    state: present

- name: Installing dependencies
  pip:
    name:
    - pymongo
    executable: pip