- name: Database configuration playbook
  gather_facts: no
  hosts: all
  become: yes
  
  tasks:
  - name: Creating database directory '/data/db'
    file:
      path: /data/db
      state: directory
  
  - name: Generating configuration files
    copy:
      src: ../files/mongod.conf-replset.tmp
      dest: /etc/mongod.conf
      owner: root
      group: root
      mode: '0644'

  - name: Removing possible locks
    file:
      path: /var/lib/mongodb/mongod.lock
      state: absent
    notify: restart mongodb

  handlers:
  - import_tasks: ../handlers/main.yml