- name: Initializing one node replica set
  mongodb_replicaset:
    login_host: localhost
    login_port: 27017
    login_user: admin
    login_password: nimda
    login_database: admin
    replica_set: rs0
    members: localhost:27017
    validate: no
  become: yes

- name: Waiting for replica set to wrap up
  pause:
    seconds: 10

- name: Creating admin user
  mongodb_user:
    database: admin
    name: admin
    password: nimda
    replica_set: rs0
    roles: root
    state: present

- name: Generating configuration files
  copy:
    src: ../files/mongod.conf-auth.tmp
    dest: /etc/mongod.conf
    owner: root
    group: root
    mode: '0644'
  become: yes

- name: Restarting MongoDB service
  service:
    name: mongod
    state: restarted
  become: yes

- name: Waiting for replica set to wrap up
  pause:
    seconds: 10

- name: Create user 'milvus'
  mongodb_user:
    login_database: admin
    login_user: admin
    login_password: nimda
    database: trac
    name: milvus
    password: suvlim
    roles: readWrite
    state: present
