- name: Updating apt cache
  apt:
    update_cache: yes

- name: Changing default py version from python2 to python3
  shell: update-alternatives --install /usr/bin/python python {{ item }}
  with_items:
  - /usr/bin/python2.7 1
  - /usr/bin/python3.6 2

- name: Installing pip3 from Ubuntu repositories
  apt:
    name: python3-pip
    state: present

- name: Installing dependencies
  pip:
    name:
    - pymongo
    executable: pip3
