- name: pip playbook
  hosts: all
  gather_facts: no

  tasks:
  - name: Changing default py version from python2 to python3
    shell: update-alternatives --install /usr/bin/python python {{ item }}
    with_items:
    - /usr/bin/python2.7 1
    - /usr/bin/python3.6 2
    become: yes

  - name: Installing pip from Ubuntu repo
    apt:
      name: python3-pip
      state: present
    become: yes

  - name: Installing dependencies
    pip:
      name:
      - pymongo
      executable: pip3
  
  - name: Waiting for dependencies to wrap up
    pause:
      seconds: 15